/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false` (hash: 1f722d6d1fb38b1b98363048770ae9c4)
interface __BaseEnv_Env {
	RECEIPTS_DB: D1Database;
	FEEDBACK_RATE_LIMIT: RateLimit;
	GITHUB_OWNER: string;
	GITHUB_REPO: string;
	ALLOWED_ORIGINS: string;
	GITHUB_APP_ID: string;
	GITHUB_INSTALLATION_ID: string;
	GITHUB_PRIVATE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_OWNER" | "GITHUB_REPO" | "ALLOWED_ORIGINS" | "GITHUB_APP_ID" | "GITHUB_INSTALLATION_ID" | "GITHUB_PRIVATE_KEY">> {}
}
