/**
 * 模块说明：
 * - 维护语义 token 到 MDI SVG path 的映射
 * 职责边界：
 * - 只提供图标实现映射，不处理回退和告警
 */
import {
  mdiAppleKeyboardShift,
  mdiAlertCircleOutline,
  mdiAlertOutline,
  mdiArrowBottomLeftThin,
  mdiArrowBottomRightThin,
  mdiArrowDownThin,
  mdiArrowCollapse,
  mdiArrowCollapseLeft,
  mdiArrowExpand,
  mdiArrowExpandAll,
  mdiArrowExpandHorizontal,
  mdiArrowExpandRight,
  mdiArrowExpandVertical,
  mdiArrowLeft,
  mdiArrowLeftThin,
  mdiArrowDown,
  mdiArrowRight,
  mdiArrowRightThin,
  mdiArrowTopLeftThin,
  mdiArrowTopRightThin,
  mdiArrowUp,
  mdiArrowUpThin,
  mdiBoxCutter,
  mdiBoxCutterOff,
  mdiCardTextOutline,
  mdiCardsOutline,
  mdiCheck,
  mdiCircleMedium,
  mdiChevronDown,
  mdiChevronRight,
  mdiChevronUp,
  mdiClose,
  mdiCodeBraces,
  mdiCodeJson,
  mdiCodeString,
  mdiCogOutline,
  mdiCompassOutline,
  mdiContentCopy,
  mdiContentSaveOutline,
  mdiCubeUnfolded,
  mdiDatabaseOutline,
  mdiDownload,
  mdiDragVariant,
  mdiDotsHorizontal,
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiFileCodeOutline,
  mdiFileCogOutline,
  mdiExport,
  mdiFileImageOutline,
  mdiImport,
  mdiFileKeyOutline,
  mdiFileMultipleOutline,
  mdiFileMinusOutline,
  mdiFileOutline,
  mdiFilePlusOutline,
  mdiFileTreeOutline,
  mdiFitToScreenOutline,
  mdiFlipToBack,
  mdiFlipToFront,
  mdiFolderImage,
  mdiFolderAlertOutline,
  mdiFolderOpenOutline,
  mdiFolderOutline,
  mdiFolderPlusOutline,
  mdiFolderStarOutline,
  mdiFolderWrenchOutline,
  mdiFormatListBulletedSquare,
  mdiFormatListGroup,
  mdiFormatAlignCenter,
  mdiFormatAlignJustify,
  mdiFormatAlignLeft,
  mdiFormatAlignRight,
  mdiFormatBold,
  mdiFormatClear,
  mdiFormatColorFill,
  mdiFormatColorHighlight,
  mdiFormatFont,
  mdiFormatFontSizeDecrease,
  mdiFormatFontSizeIncrease,
  mdiFormatItalic,
  mdiFormatStrikethrough,
  mdiFormatUnderline,
  mdiFormatVerticalAlignBottom,
  mdiFormatVerticalAlignCenter,
  mdiFormatVerticalAlignTop,
  mdiFullscreen,
  mdiFullscreenExit,
  mdiGrid,
  mdiGridOff,
  mdiFormatText,
  mdiFormatTextVariantOutline,
  mdiHelpCircleOutline,
  mdiHumanGreeting,
  mdiImageFilterCenterFocus,
  mdiImageFilterCenterFocusWeak,
  mdiImageOutline,
  mdiKeyboardSpace,
  mdiLandRowsHorizontal,
  mdiLandRowsVertical,
  mdiImageMinusOutline,
  mdiImagePlusOutline,
  mdiQrcodeScan,
  mdiShapeOutline,
  mdiKeyOutline,
  mdiLanguageCss3,
  mdiLanguageHtml5,
  mdiLanguageJavascript,
  mdiLanguageMarkdownOutline,
  mdiLanguageTypescript,
  mdiLayersOutline,
  mdiLockOutline,
  mdiMagnify,
  mdiMagnifyMinusOutline,
  mdiMagnifyPlusOutline,
  mdiMagnet,
  mdiMagnetOn,
  mdiMouseScrollWheel,
  mdiMinus,
  mdiNumeric,
  mdiPackageVariant,
  mdiPackageVariantClosed,
  mdiPaperCutVertical,
  mdiPaletteOutline,
  mdiPencilOutline,
  mdiPencilRuler,
  mdiPinOffOutline,
  mdiPinOutline,
  mdiPlayOutline,
  mdiPlus,
  mdiRefresh,
  mdiRedoVariant,
  mdiRestart,
  mdiRocketLaunchOutline,
  mdiSortAlphabeticalAscending,
  mdiSourceBranch,
  mdiSourceCommit,
  mdiSwapHorizontal,
  mdiTableLarge,
  mdiToggleSwitchOutline,
  mdiTextBoxOutline,
  mdiDeleteVariant,
  mdiUndoVariant,
  mdiViewDashboard,
  mdiViewDashboardEditOutline,
  mdiViewDashboardOutline,
  mdiViewGridOutline,
  mdiViewSequentialOutline,
  mdiVariable,
  mdiVuejs,
  mdiWindowMaximize,
  mdiWindowMinimize,
  mdiWindowRestore,
  mdiXml,
} from '@mdi/js'
import type { IconToken } from './iconTokens'
import type { IconGlyph } from './icon.types'

function glyph(path: string, viewBox?: string): IconGlyph {
  return { path, viewBox }
}

export const iconGlyphs = {
  'action.add': glyph(mdiPlus),
  'action.check': glyph(mdiCheck),
  'action.close': glyph(mdiClose),
  'action.copy': glyph(mdiContentCopy, '-1 -1 26 26'),
  'action.delete': glyph(mdiDeleteVariant),
  'action.discard': glyph(mdiUndoVariant),
  'action.download': glyph(mdiDownload),
  'action.drag': glyph(mdiDragVariant),
  'action.edit': glyph(mdiPencilOutline),
  'action.export': glyph(mdiExport),
  'action.folder-plus': glyph(mdiFolderPlusOutline),
  'action.file-minus': glyph(mdiFileMinusOutline),
  'action.file-plus': glyph(mdiFilePlusOutline),
  'action.image-minus': glyph(mdiImageMinusOutline),
  'action.image-plus': glyph(mdiImagePlusOutline),
  'action.import': glyph(mdiImport),
  'action.remove': glyph(mdiMinus),
  'action.play': glyph(mdiPlayOutline),
  'action.search': glyph(mdiMagnify),
  'action.publish': glyph(mdiRocketLaunchOutline),
  'action.refresh': glyph(mdiRefresh),
  'action.restart': glyph(mdiRestart),
  'action.redo': glyph(mdiRedoVariant),
  'action.save': glyph(mdiContentSaveOutline),
  'action.sort-alphabetical-ascending': glyph(mdiSortAlphabeticalAscending),
  'action.sort-category': glyph(mdiFormatListGroup),
  'action.undo': glyph(mdiUndoVariant),

  'nav.arrow-left': glyph(mdiArrowLeft),
  'nav.arrow-down': glyph(mdiArrowDown),
  'nav.arrow-right': glyph(mdiArrowRight),
  'nav.arrow-swap': glyph(mdiSwapHorizontal),
  'nav.arrow-up': glyph(mdiArrowUp),
  'nav.chevron-down': glyph(mdiChevronDown),
  'nav.chevron-up': glyph(mdiChevronUp),
  'nav.compass': glyph(mdiCompassOutline),
  'nav.files': glyph(mdiFileMultipleOutline),
  'nav.more': glyph(mdiDotsHorizontal),
  'nav.sidebar-collapse': glyph(mdiArrowCollapseLeft),
  'nav.sidebar-expand': glyph(mdiArrowExpandRight),
  'nav.welcome': glyph(mdiHumanGreeting),
  'nav.workbench': glyph(mdiPencilRuler),

  'window.fullscreen': glyph(mdiFullscreen),
  'window.fullscreen-exit': glyph(mdiFullscreenExit),
  'window.maximize': glyph(mdiWindowMaximize),
  'window.minimize': glyph(mdiWindowMinimize),
  'window.restore': glyph(mdiWindowRestore),

  'tree.chevron-down': glyph(mdiChevronDown),
  'tree.chevron-right': glyph(mdiChevronRight),

  'tool.clip': glyph(mdiPaperCutVertical),
  'tool.box-cutter': glyph(mdiBoxCutter),
  'tool.box-cutter-off': glyph(mdiBoxCutterOff),
  'tool.fit-screen': glyph(mdiFitToScreenOutline),
  'tool.focus-selection': glyph(mdiImageFilterCenterFocusWeak),
  'tool.flip-to-back': glyph(mdiFlipToBack),
  'tool.flip-to-front': glyph(mdiFlipToFront),
  'tool.grid': glyph(mdiGrid),
  'tool.grid-off': glyph(mdiGridOff),
  'tool.snap-grid': glyph(mdiMagnet),
  'tool.snap-grid-on': glyph(mdiMagnetOn),
  'tool.pin': glyph(mdiPinOutline),
  'tool.pin-off': glyph(mdiPinOffOutline),
  'tool.pixelated': glyph(mdiCubeUnfolded),
  'tool.settings': glyph(mdiCogOutline),
  'tool.zoom-in': glyph(mdiMagnifyPlusOutline),
  'tool.zoom-out': glyph(mdiMagnifyMinusOutline),

  'input.mouse-scroll-wheel': glyph(mdiMouseScrollWheel),
  'input.keyboard-space': glyph(mdiKeyboardSpace),
  'input.keyboard-shift': glyph(mdiAppleKeyboardShift),

  'layout.fill': glyph(mdiArrowExpandAll),
  'layout.fill-horizontal': glyph(mdiArrowExpandHorizontal),
  'layout.fill-vertical': glyph(mdiArrowExpandVertical),
  'layout.center': glyph(mdiImageFilterCenterFocus),
  'layout.inset': glyph(mdiArrowCollapse),
  'layout.outset': glyph(mdiArrowExpand),
  'layout.columns': glyph(mdiLandRowsVertical),
  'layout.rows': glyph(mdiLandRowsHorizontal),

  'data.collection': glyph(mdiDatabaseOutline),
  'data.code-string': glyph(mdiCodeString),
  'data.layers': glyph(mdiLayersOutline),
  'data.list-selection': glyph(mdiFormatListBulletedSquare),
  'data.list-tree': glyph(mdiFileTreeOutline),
  'data.table': glyph(mdiTableLarge),
  'data.version': glyph(mdiSourceCommit),
  'data.symbol-boolean': glyph(mdiToggleSwitchOutline),
  'data.symbol-class': glyph(mdiCodeBraces),
  'data.symbol-color': glyph(mdiPaletteOutline),
  'data.symbol-key': glyph(mdiKeyOutline),
  'data.symbol-number': glyph(mdiNumeric),
  'data.symbol-string': glyph(mdiFormatText),
  'data.variable': glyph(mdiVariable),

  'format.align-start': glyph(mdiFormatAlignLeft),
  'format.align-center': glyph(mdiFormatAlignCenter),
  'format.align-end': glyph(mdiFormatAlignRight),
  'format.align-justify': glyph(mdiFormatAlignJustify),
  'format.bold': glyph(mdiFormatBold),
  'format.clear': glyph(mdiFormatClear),
  'format.code-braces': glyph(mdiCodeBraces),
  'format.color-fill': glyph(mdiFormatColorFill),
  'format.color-highlight': glyph(mdiFormatColorHighlight),
  'format.font-size-decrease': glyph(mdiFormatFontSizeDecrease),
  'format.font-size-increase': glyph(mdiFormatFontSizeIncrease),
  'format.italic': glyph(mdiFormatItalic),
  'format.strikethrough': glyph(mdiFormatStrikethrough),
  'format.underline': glyph(mdiFormatUnderline),
  'format.text-variant-outline': glyph(mdiFormatTextVariantOutline),
  'format.xml': glyph(mdiXml),
  'format.vertical-top': glyph(mdiFormatVerticalAlignTop),
  'format.vertical-center': glyph(mdiFormatVerticalAlignCenter),
  'format.vertical-bottom': glyph(mdiFormatVerticalAlignBottom),
  'format.anchor-top-left': glyph(mdiArrowTopLeftThin),
  'format.anchor-top': glyph(mdiArrowUpThin),
  'format.anchor-top-right': glyph(mdiArrowTopRightThin),
  'format.anchor-left': glyph(mdiArrowLeftThin),
  'format.anchor-center': glyph(mdiCircleMedium),
  'format.anchor-right': glyph(mdiArrowRightThin),
  'format.anchor-bottom-left': glyph(mdiArrowBottomLeftThin),
  'format.anchor-bottom': glyph(mdiArrowDownThin),
  'format.anchor-bottom-right': glyph(mdiArrowBottomRightThin),

  'entity.block-flow-container': glyph(mdiViewSequentialOutline),
  'entity.block-custom': glyph(mdiPackageVariantClosed),
  'entity.block-image': glyph(mdiImageOutline),
  'entity.block-markdown': glyph(mdiLanguageMarkdownOutline),
  'entity.block-package': glyph(mdiPackageVariantClosed),
  'entity.block-qrcode': glyph(mdiQrcodeScan),
  'entity.block-shape': glyph(mdiShapeOutline),
  'entity.block-simple-container': glyph(mdiViewGridOutline),
  'entity.block-text': glyph(mdiTextBoxOutline),
  'entity.card-blueprint': glyph(mdiViewDashboard),
  'entity.card-instance': glyph(mdiViewDashboardEditOutline),

  'status.error': glyph(mdiAlertCircleOutline),
  'status.change-added': glyph(mdiPlus),
  'status.change-removed': glyph(mdiMinus),
  'status.eye': glyph(mdiEyeOutline),
  'status.eye-off': glyph(mdiEyeOffOutline),
  'status.folder-open': glyph(mdiFolderOpenOutline),
  'status.folder-alert': glyph(mdiFolderAlertOutline),
  'status.unknown': glyph(mdiHelpCircleOutline),
  'status.warning': glyph(mdiAlertOutline),

  'file.css': glyph(mdiLanguageCss3),
  'file.custom-block': glyph(mdiPackageVariantClosed),
  'file.env': glyph(mdiFileKeyOutline),
  'file.font': glyph(mdiFormatFont),
  'file.generic': glyph(mdiFileOutline),
  'file.git': glyph(mdiSourceBranch),
  'file.html': glyph(mdiLanguageHtml5),
  'file.image': glyph(mdiFileImageOutline),
  'file.javascript': glyph(mdiLanguageJavascript),
  'file.json': glyph(mdiCodeJson),
  'file.lock': glyph(mdiLockOutline),
  'file.markdown': glyph(mdiLanguageMarkdownOutline),
  'file.media': glyph(mdiFileImageOutline),
  'file.opencard': glyph(mdiCardsOutline),
  'file.opencard-project': glyph(mdiFileCogOutline),
  'file.package': glyph(mdiPackageVariantClosed),
  'file.package-variant': glyph(mdiPackageVariant),
  'file.settings': glyph(mdiCogOutline),
  'file.text': glyph(mdiCardTextOutline),
  'file.typescript': glyph(mdiLanguageTypescript),
  'file.vue': glyph(mdiVuejs),

  'folder.assets': glyph(mdiFolderImage),
  'folder.components': glyph(mdiFolderStarOutline),
  'folder.core': glyph(mdiFolderWrenchOutline),
  'folder.generic': glyph(mdiFolderOutline),
  'folder.locales': glyph(mdiFolderOutline),
  'folder.open': glyph(mdiFolderOpenOutline),
  'folder.src': glyph(mdiFileCodeOutline),
  'folder.views': glyph(mdiViewDashboardOutline),
} satisfies Record<IconToken, IconGlyph>
