/**
 * 模块说明：
 * - 定义项目唯一图标语义 token 列表
 * 职责边界：
 * - 只声明语义键，不绑定具体图标库实现
 */
export const iconTokens = {
  'action.add': true,
  'action.check': true,
  'action.close': true,
  'action.copy': true,
  'action.delete': true,
  'action.discard': true,
  'action.edit': true,
  'action.export': true,
  'action.play': true,
  'action.publish': true,
  'action.refresh': true,
  'action.restart': true,
  'action.save': true,

  'nav.arrow-left-right': true,
  'nav.arrow-right': true,
  'nav.arrow-swap': true,
  'nav.arrow-up': true,
  'nav.chevron-down': true,
  'nav.chevron-left': true,
  'nav.chevron-right': true,
  'nav.compass': true,
  'nav.files': true,
  'nav.menu': true,

  'tree.chevron-down': true,
  'tree.chevron-right': true,

  'tool.search': true,
  'tool.settings': true,
  'tool.settings-gear': true,

  'data.collection': true,
  'data.layers': true,
  'data.list-selection': true,
  'data.list-tree': true,
  'data.symbol-boolean': true,
  'data.symbol-class': true,
  'data.symbol-color': true,
  'data.symbol-key': true,
  'data.symbol-number': true,
  'data.symbol-string': true,

  'entity.account': true,

  'status.error': true,
  'status.eye': true,
  'status.folder-open': true,
  'status.source-control': true,
  'status.star': true,
  'status.unknown': true,
  'status.warning': true,
  'status.watching': true,

  'file.default': true,
  'file.code': true,
  'file.css': true,
  'file.env': true,
  'file.generic': true,
  'file.git': true,
  'file.html': true,
  'file.image': true,
  'file.javascript': true,
  'file.json': true,
  'file.lock': true,
  'file.markdown': true,
  'file.media': true,
  'file.opencard': true,
  'file.package': true,
  'file.settings': true,
  'file.text': true,
  'file.typescript': true,
  'file.vue': true,

  'folder.assets': true,
  'folder.assets-expanded': true,
  'folder.components': true,
  'folder.components-expanded': true,
  'folder.core': true,
  'folder.core-expanded': true,
  'folder.default': true,
  'folder.default-expanded': true,
  'folder.generic': true,
  'folder.generic-opened': true,
  'folder.locales': true,
  'folder.locales-expanded': true,
  'folder.src': true,
  'folder.src-expanded': true,
  'folder.views': true,
  'folder.views-expanded': true,
} as const

export type IconToken = keyof typeof iconTokens
