/**
 * 模块说明：
 * - 维护语义 token 到 MDI SVG path 的映射
 * 职责边界：
 * - 只提供图标实现映射，不处理回退和告警
 */
import {
  mdiAccountOutline,
  mdiAlertCircleOutline,
  mdiAlertOutline,
  mdiArrowLeftRight,
  mdiArrowBottomLeftThin,
  mdiArrowBottomRightThin,
  mdiArrowDownThin,
  mdiArrowLeft,
  mdiArrowLeftThin,
  mdiArrowDown,
  mdiArrowRight,
  mdiArrowRightThin,
  mdiArrowTopLeftThin,
  mdiArrowTopRightThin,
  mdiArrowUp,
  mdiArrowUpThin,
  mdiCardTextOutline,
  mdiCardsOutline,
  mdiCheck,
  mdiCircleMedium,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiClose,
  mdiCodeBraces,
  mdiCodeJson,
  mdiCog,
  mdiCogOutline,
  mdiCompassOutline,
  mdiContentCopy,
  mdiContentSaveOutline,
  mdiCropFree,
  mdiCropSquare,
  mdiDatabaseOutline,
  mdiDockLeft,
  mdiDownload,
  mdiDotsHorizontal,
  mdiExport,
  mdiEyeCheckOutline,
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiFileCodeOutline,
  mdiFileCogOutline,
  mdiFileImageOutline,
  mdiFileKeyOutline,
  mdiFileMultipleOutline,
  mdiFileMinusOutline,
  mdiFileOutline,
  mdiFilePlusOutline,
  mdiFileTreeOutline,
  mdiFitToScreenOutline,
  mdiFolderImage,
  mdiFolderAlertOutline,
  mdiFolderOpenOutline,
  mdiFolderOutline,
  mdiFolderPlusOutline,
  mdiFolderStarOutline,
  mdiFolderWrenchOutline,
  mdiFormatListBulletedSquare,
  mdiFormatAlignCenter,
  mdiFormatAlignJustify,
  mdiFormatAlignLeft,
  mdiFormatAlignRight,
  mdiFormatVerticalAlignBottom,
  mdiFormatVerticalAlignCenter,
  mdiFormatVerticalAlignTop,
  mdiFullscreen,
  mdiFullscreenExit,
  mdiFormatText,
  mdiHelpCircleOutline,
  mdiImageOutline,
  mdiImageMinusOutline,
  mdiImagePlusOutline,
  mdiImport,
  mdiQrcode,
  mdiShapeOutline,
  mdiKeyOutline,
  mdiLandPlots,
  mdiLanguageCss3,
  mdiLanguageHtml5,
  mdiLanguageJavascript,
  mdiLanguageMarkdownOutline,
  mdiLanguageTypescript,
  mdiLayersOutline,
  mdiLockOutline,
  mdiMagnify,
  mdiMagnifyMinusOutline,
  mdiMagnifyPlusOutline,
  mdiMenu,
  mdiNumeric,
  mdiPackageVariantClosed,
  mdiPaletteOutline,
  mdiPencilOutline,
  mdiPinOffOutline,
  mdiPinOutline,
  mdiPlayOutline,
  mdiPlus,
  mdiRefresh,
  mdiRedoVariant,
  mdiRestart,
  mdiRocketLaunchOutline,
  mdiSortAlphabeticalAscending,
  mdiSourceBranch,
  mdiStarOutline,
  mdiSwapHorizontal,
  mdiToggleSwitchOutline,
  mdiTextBoxOutline,
  mdiTrashCanOutline,
  mdiUndoVariant,
  mdiViewDashboard,
  mdiViewDashboardEditOutline,
  mdiViewDashboardOutline,
  mdiVariable,
  mdiVuejs,
  mdiWindowMaximize,
  mdiWindowMinimize,
  mdiWindowRestore,
} from '@mdi/js'
import type { IconToken } from './iconTokens'
import type { IconGlyph } from './iconTypes'

function glyph(path: string): IconGlyph {
  return { path }
}

export const iconGlyphs = {
  'action.add': glyph(mdiPlus),
  'action.check': glyph(mdiCheck),
  'action.close': glyph(mdiClose),
  'action.copy': glyph(mdiContentCopy),
  'action.delete': glyph(mdiTrashCanOutline),
  'action.discard': glyph(mdiUndoVariant),
  'action.download': glyph(mdiDownload),
  'action.edit': glyph(mdiPencilOutline),
  'action.export': glyph(mdiExport),
  'action.folder-plus': glyph(mdiFolderPlusOutline),
  'action.file-minus': glyph(mdiFileMinusOutline),
  'action.file-plus': glyph(mdiFilePlusOutline),
  'action.image-minus': glyph(mdiImageMinusOutline),
  'action.image-plus': glyph(mdiImagePlusOutline),
  'action.import': glyph(mdiImport),
  'action.play': glyph(mdiPlayOutline),
  'action.publish': glyph(mdiRocketLaunchOutline),
  'action.refresh': glyph(mdiRefresh),
  'action.restart': glyph(mdiRestart),
  'action.redo': glyph(mdiRedoVariant),
  'action.save': glyph(mdiContentSaveOutline),
  'action.sort-alphabetical-ascending': glyph(mdiSortAlphabeticalAscending),
  'action.undo': glyph(mdiUndoVariant),

  'nav.arrow-left-right': glyph(mdiArrowLeftRight),
  'nav.arrow-left': glyph(mdiArrowLeft),
  'nav.arrow-down': glyph(mdiArrowDown),
  'nav.arrow-right': glyph(mdiArrowRight),
  'nav.arrow-swap': glyph(mdiSwapHorizontal),
  'nav.arrow-up': glyph(mdiArrowUp),
  'nav.chevron-down': glyph(mdiChevronDown),
  'nav.chevron-left': glyph(mdiChevronLeft),
  'nav.chevron-right': glyph(mdiChevronRight),
  'nav.chevron-up': glyph(mdiChevronUp),
  'nav.compass': glyph(mdiCompassOutline),
  'nav.files': glyph(mdiFileMultipleOutline),
  'nav.menu': glyph(mdiMenu),
  'nav.more': glyph(mdiDotsHorizontal),
  'nav.sidebar-collapse': glyph(mdiDockLeft),
  'nav.sidebar-expand': glyph(mdiDockLeft),

  'window.fullscreen': glyph(mdiFullscreen),
  'window.fullscreen-exit': glyph(mdiFullscreenExit),
  'window.maximize': glyph(mdiWindowMaximize),
  'window.minimize': glyph(mdiWindowMinimize),
  'window.restore': glyph(mdiWindowRestore),

  'tree.chevron-down': glyph(mdiChevronDown),
  'tree.chevron-right': glyph(mdiChevronRight),

  'tool.search': glyph(mdiMagnify),
  'tool.clip-off': glyph(mdiCropFree),
  'tool.clip-on': glyph(mdiCropSquare),
  'tool.fit-screen': glyph(mdiFitToScreenOutline),
  'tool.pin': glyph(mdiPinOutline),
  'tool.pin-off': glyph(mdiPinOffOutline),
  'tool.settings': glyph(mdiCogOutline),
  'tool.settings-gear': glyph(mdiCog),
  'tool.zoom-in': glyph(mdiMagnifyPlusOutline),
  'tool.zoom-out': glyph(mdiMagnifyMinusOutline),

  'data.collection': glyph(mdiDatabaseOutline),
  'data.layers': glyph(mdiLayersOutline),
  'data.list-selection': glyph(mdiFormatListBulletedSquare),
  'data.list-tree': glyph(mdiFileTreeOutline),
  'data.symbol-boolean': glyph(mdiToggleSwitchOutline),
  'data.symbol-class': glyph(mdiCodeBraces),
  'data.symbol-color': glyph(mdiPaletteOutline),
  'data.symbol-key': glyph(mdiKeyOutline),
  'data.symbol-number': glyph(mdiNumeric),
  'data.symbol-string': glyph(mdiFormatText),
  'data.variable': glyph(mdiVariable),

  'format.align-start': glyph(mdiFormatAlignLeft),
  'format.align-center': glyph(mdiFormatAlignCenter),
  'format.align-end': glyph(mdiFormatAlignRight),
  'format.align-justify': glyph(mdiFormatAlignJustify),
  'format.vertical-top': glyph(mdiFormatVerticalAlignTop),
  'format.vertical-center': glyph(mdiFormatVerticalAlignCenter),
  'format.vertical-bottom': glyph(mdiFormatVerticalAlignBottom),
  'format.anchor-top-left': glyph(mdiArrowTopLeftThin),
  'format.anchor-top': glyph(mdiArrowUpThin),
  'format.anchor-top-right': glyph(mdiArrowTopRightThin),
  'format.anchor-left': glyph(mdiArrowLeftThin),
  'format.anchor-center': glyph(mdiCircleMedium),
  'format.anchor-right': glyph(mdiArrowRightThin),
  'format.anchor-bottom-left': glyph(mdiArrowBottomLeftThin),
  'format.anchor-bottom': glyph(mdiArrowDownThin),
  'format.anchor-bottom-right': glyph(mdiArrowBottomRightThin),

  'entity.account': glyph(mdiAccountOutline),
  'entity.block-image': glyph(mdiImageOutline),
  'entity.block-qrcode': glyph(mdiQrcode),
  'entity.block-shape': glyph(mdiShapeOutline),
  'entity.block-simple-container': glyph(mdiLandPlots),
  'entity.block-text': glyph(mdiTextBoxOutline),
  'entity.card-blueprint': glyph(mdiViewDashboard),
  'entity.card-instance': glyph(mdiViewDashboardEditOutline),

  'status.error': glyph(mdiAlertCircleOutline),
  'status.eye': glyph(mdiEyeOutline),
  'status.eye-off': glyph(mdiEyeOffOutline),
  'status.folder-open': glyph(mdiFolderOpenOutline),
  'status.folder-alert': glyph(mdiFolderAlertOutline),
  'status.source-control': glyph(mdiSourceBranch),
  'status.star': glyph(mdiStarOutline),
  'status.unknown': glyph(mdiHelpCircleOutline),
  'status.warning': glyph(mdiAlertOutline),
  'status.watching': glyph(mdiEyeCheckOutline),

  'file.default': glyph(mdiFileOutline),
  'file.code': glyph(mdiFileCodeOutline),
  'file.css': glyph(mdiLanguageCss3),
  'file.env': glyph(mdiFileKeyOutline),
  'file.generic': glyph(mdiFileOutline),
  'file.git': glyph(mdiSourceBranch),
  'file.html': glyph(mdiLanguageHtml5),
  'file.image': glyph(mdiFileImageOutline),
  'file.javascript': glyph(mdiLanguageJavascript),
  'file.json': glyph(mdiCodeJson),
  'file.lock': glyph(mdiLockOutline),
  'file.markdown': glyph(mdiLanguageMarkdownOutline),
  'file.media': glyph(mdiFileImageOutline),
  'file.opencard': glyph(mdiCardsOutline),
  'file.opencard-project': glyph(mdiFileCogOutline),
  'file.package': glyph(mdiPackageVariantClosed),
  'file.settings': glyph(mdiCogOutline),
  'file.text': glyph(mdiCardTextOutline),
  'file.typescript': glyph(mdiLanguageTypescript),
  'file.vue': glyph(mdiVuejs),

  'folder.assets': glyph(mdiFolderImage),
  'folder.assets-expanded': glyph(mdiFolderOpenOutline),
  'folder.components': glyph(mdiFolderStarOutline),
  'folder.components-expanded': glyph(mdiFolderOpenOutline),
  'folder.core': glyph(mdiFolderWrenchOutline),
  'folder.core-expanded': glyph(mdiFolderOpenOutline),
  'folder.default': glyph(mdiFolderOutline),
  'folder.default-expanded': glyph(mdiFolderOpenOutline),
  'folder.generic': glyph(mdiFolderOutline),
  'folder.generic-opened': glyph(mdiFolderOpenOutline),
  'folder.locales': glyph(mdiFolderOutline),
  'folder.locales-expanded': glyph(mdiFolderOpenOutline),
  'folder.src': glyph(mdiFileCodeOutline),
  'folder.src-expanded': glyph(mdiFolderOpenOutline),
  'folder.views': glyph(mdiViewDashboardOutline),
  'folder.views-expanded': glyph(mdiFolderOpenOutline),
} satisfies Record<IconToken, IconGlyph>
