/**
 * 模块说明：
 * - 定义项目唯一图标语义 token 列表
 * 职责边界：
 * - 只声明语义键，不绑定具体图标库实现
 */
export const iconTokens = {
  'action.add': true,
  'action.check': true,
  'action.close': true,
  'action.copy': true,
  'action.delete': true,
  'action.discard': true,
  'action.download': true,
  'action.drag': true,
  'action.edit': true,
  'action.export': true,
  'action.folder-plus': true,
  'action.file-minus': true,
  'action.file-plus': true,
  'action.image-minus': true,
  'action.image-plus': true,
  'action.import': true,
  'action.play': true,
  'action.search': true,
  'action.publish': true,
  'action.refresh': true,
  'action.restart': true,
  'action.redo': true,
  'action.save': true,
  'action.sort-alphabetical-ascending': true,
  'action.sort-category': true,
  'action.undo': true,

  'nav.arrow-left': true,
  'nav.arrow-down': true,
  'nav.arrow-right': true,
  'nav.arrow-swap': true,
  'nav.arrow-up': true,
  'nav.chevron-down': true,
  'nav.chevron-up': true,
  'nav.compass': true,
  'nav.files': true,
  'nav.more': true,
  'nav.sidebar-collapse': true,
  'nav.sidebar-expand': true,
  'nav.welcome': true,
  'nav.workbench': true,

  'window.fullscreen': true,
  'window.fullscreen-exit': true,
  'window.maximize': true,
  'window.minimize': true,
  'window.restore': true,

  'tree.chevron-down': true,
  'tree.chevron-right': true,

  'tool.clip': true,
  'tool.box-cutter': true,
  'tool.box-cutter-off': true,
  'tool.fit-screen': true,
  'tool.focus-selection': true,
  'tool.flip-to-back': true,
  'tool.flip-to-front': true,
  'tool.grid': true,
  'tool.grid-off': true,
  'tool.snap-grid': true,
  'tool.snap-grid-on': true,
  'tool.pin': true,
  'tool.pin-off': true,
  'tool.pixelated': true,
  'tool.settings': true,
  'tool.zoom-in': true,
  'tool.zoom-out': true,

  'input.mouse-scroll-wheel': true,
  'input.keyboard-space': true,
  'input.keyboard-shift': true,

  'layout.fill': true,
  'layout.fill-horizontal': true,
  'layout.fill-vertical': true,
  'layout.center': true,
  'layout.inset': true,
  'layout.outset': true,
  'layout.columns': true,
  'layout.rows': true,

  'data.collection': true,
  'data.code-string': true,
  'data.layers': true,
  'data.list-bulleted': true,
  'data.list-numbered': true,
  'data.list-selection': true,
  'data.list-tree': true,
  'data.table': true,
  'data.symbol-boolean': true,
  'data.symbol-class': true,
  'data.symbol-color': true,
  'data.symbol-key': true,
  'data.symbol-number': true,
  'data.symbol-string': true,
  'data.symbol-custom-block': true,
  'data.variable': true,

  'format.align-start': true,
  'format.align-center': true,
  'format.align-end': true,
  'format.align-justify': true,
  'format.bold': true,
  'format.clear': true,
  'format.code-braces': true,
  'format.color-fill': true,
  'format.color-highlight': true,
  'format.font-size-decrease': true,
  'format.font-size-increase': true,
  'format.italic': true,
  'format.strikethrough': true,
  'format.underline': true,
  'format.text-variant-outline': true,
  'format.xml': true,
  'format.vertical-top': true,
  'format.vertical-center': true,
  'format.vertical-bottom': true,
  'format.anchor-top-left': true,
  'format.anchor-top': true,
  'format.anchor-top-right': true,
  'format.anchor-left': true,
  'format.anchor-center': true,
  'format.anchor-right': true,
  'format.anchor-bottom-left': true,
  'format.anchor-bottom': true,
  'format.anchor-bottom-right': true,

  'entity.block-flow-container': true,
  'entity.block-custom': true,
  'entity.block-image': true,
  'entity.block-markdown': true,
  'entity.block-package': true,
  'entity.block-qrcode': true,
  'entity.block-shape': true,
  'entity.block-simple-container': true,
  'entity.block-text': true,
  'entity.card-blueprint': true,
  'entity.card-instance': true,

  'status.error': true,
  'status.eye': true,
  'status.eye-off': true,
  'status.folder-open': true,
  'status.folder-alert': true,
  'status.unknown': true,
  'status.warning': true,

  'file.css': true,
  'file.custom-block': true,
  'file.dictionary': true,
  'file.env': true,
  'file.font': true,
  'file.generic': true,
  'file.git': true,
  'file.html': true,
  'file.image': true,
  'file.javascript': true,
  'file.json': true,
  'file.lock': true,
  'file.markdown': true,
  'file.media': true,
  'file.opencard': true,
  'file.opencard-project': true,
  'file.package': true,
  'file.project-icon': true,
  'file.settings': true,
  'file.text': true,
  'file.typescript': true,
  'file.vue': true,

  'folder.assets': true,
  'folder.components': true,
  'folder.core': true,
  'folder.generic': true,
  'folder.locales': true,
  'folder.open': true,
  'folder.src': true,
  'folder.views': true,
} as const

export type IconToken = keyof typeof iconTokens
