/**
 * 主题实例 — 深色与浅色主题的完整 token 值映射。
 */
import type { OcThemeId, OcThemeTokens } from './themeTokens'

export const OC_SHARED_THEME_TOKENS = {
  '--oc-scrollbar-size': '8px',
  '--oc-bg-accent': '#A260FF',
  '--oc-bg-glass-blur': '18px',
  '--oc-bg-glass-saturate': '120%',
  '--oc-border-accent': '#A260FF',
  '--oc-accent': '#A260FF',
  '--oc-accent-neighbor': '#60A2FF',
  '--oc-accent-fg': '#f5f2ff',
  '--oc-icon-default': 'currentColor',
  '--oc-icon-size-sm': '12px',
  '--oc-icon-size-md': '16px',
  '--oc-icon-size-lg': '20px',
  '--oc-icon-size-action': '16px',
  '--oc-field-affix-icon-offset-y': '-1px',
  '--oc-number-badge-size': '11px',
  '--oc-number-badge-padding-inline': '2px',
  '--oc-number-badge-font-size': '7px',
  '--oc-number-badge-line-height': '9px',
  '--oc-inline-key-height': '18px',
  '--oc-inline-key-padding-inline': '5px',
  '--oc-inline-key-highlight': 'color-mix(in srgb, var(--oc-fg-default) 18%, transparent)',
  '--oc-inline-key-lowlight': 'color-mix(in srgb, var(--oc-border-strong) 46%, transparent)',
  '--oc-inline-key-shadow-offset': '3px',
  '--oc-font-sans': '"Segoe UI Variable Text", "SF Pro Text", "Inter", "PingFang SC", "Microsoft YaHei UI", "Noto Sans CJK SC", sans-serif',
  '--oc-font-mono': '"Cascadia Code", "JetBrains Mono", "SF Mono", "Consolas", "Fira Code", monospace',
  '--oc-text-xs': '10px',
  '--oc-text-sm': '11px',
  '--oc-text-base': '12px',
  '--oc-text-lg': '13px',
  '--oc-text-xl': '16px',
  '--oc-font-preview-size': '48px',
  '--oc-space-1': '4px',
  '--oc-space-2': '6px',
  '--oc-space-3': '8px',
  '--oc-space-4': '12px',
  '--oc-space-5': '16px',
  '--oc-space-6': '20px',
  '--oc-space-8': '32px',
  '--oc-tree-indent': '14px',
  '--oc-tree-action-label-min-width': '64px',
  '--oc-size-sm': '22px',
  '--oc-size-md': '28px',
  '--oc-size-lg': '36px',
  '--oc-color-picker-plane-height': '132px',
  '--oc-color-channel-track-height': '12px',
  '--oc-color-channel-handle-width': '8px',
  '--oc-color-channel-handle-height': '16px',
  '--oc-color-channel-handle-border-width': '2px',
  '--oc-color-channel-handle-border-color': '#FFFFFF',
  '--oc-color-channel-handle-shadow': '0 0 0 1px rgb(0 0 0 / 55%)',
  '--oc-list-max-height-sm': '144px',
  '--oc-list-max-height-md': '240px',
  '--oc-list-max-height-lg': '320px',
  '--oc-content-width-md': '720px',
  '--oc-settings-preview-height-lg': '360px',
  '--oc-settings-preview-height-md': '240px',
  '--oc-settings-preview-shrink-distance': '240px',
  '--oc-settings-preview-sticky-offset': '0px',
  '--oc-settings-preview-glass-opacity-min': '0',
  '--oc-settings-preview-glass-opacity-max': '1',
  '--oc-z-settings-preview': '2',
  '--oc-project-outline-width': '168px',
  '--oc-project-font-list-min-width': '280px',
  '--oc-project-font-list-width': '48%',
  '--oc-project-icon-atlas-height': '240px',
  '--oc-project-icon-property-min-width': '280px',
  '--oc-project-icon-inspector-min-height': '240px',
  '--oc-project-icon-workbench-series-width': '48%',
  '--oc-project-icon-workbench-inspector-width': '320px',
  '--oc-project-icon-workbench-icon-list-height': '280px',
  '--oc-project-icon-preview-size': '128px',
  '--oc-custom-block-list-min-width': '220px',
  '--oc-custom-block-list-width': '280px',
  '--oc-custom-block-property-height': '320px',
  '--oc-custom-block-export-fields-max-height': '320px',
  '--oc-viewport-inspector-min-height': '180px',
  '--oc-viewport-inspector-visible-min-height': '160px',
  '--oc-z-viewport-inspector': '2',
  '--oc-floating-surface-padding': '4px',
  '--oc-floating-surface-gap': '6px',
  '--oc-card-editor-dock-min-width': '280px',
  '--oc-card-editor-dock-max-width': '420px',
  '--oc-card-editor-dock-default-width': '320px',
  '--oc-card-editor-dock-expand-threshold': '28px',
  '--oc-card-editor-dock-collapse-threshold': '70px',
  '--oc-card-editor-dock-top-min-height': '160px',
  '--oc-card-editor-dock-bottom-min-height': '220px',
  '--oc-card-editor-dock-responsive-width': '720px',
  '--oc-overlay-toolbar-field-min-width': '48px',
  '--oc-overlay-toolbar-field-max-width': '56px',
  '--oc-autocomplete-popover-min-width': '240px',
  '--oc-json-editor-min-height': '180px',
  '--oc-json-editor-array-min-height': '220px',
  '--oc-dialog-width-sm': '360px',
  '--oc-dialog-width-md': '520px',
  '--oc-dialog-width-lg': '720px',
  '--oc-dialog-width-xl': '860px',
  '--oc-dialog-height-sm': '240px',
  '--oc-dialog-height-md': '360px',
  '--oc-dialog-height-lg': '560px',
  '--oc-dialog-height-workspace': '400px',
  '--oc-dialog-max-height': '720px',
  '--oc-dialog-header-padding-block': '8px',
  '--oc-dialog-header-padding-inline': '12px',
  '--oc-dialog-body-padding': '12px',
  '--oc-dialog-body-gap': '8px',
  '--oc-dialog-footer-padding-block': '8px',
  '--oc-dialog-footer-padding-inline': '12px',
  '--oc-z-modal': '1000',
  '--oc-z-overlay-toolbar': '3',
  '--oc-viewport-dot-pattern': 'radial-gradient(circle at center, color-mix(in srgb, var(--oc-fg-subtle) 38%, transparent) 1px, transparent 1.25px)',
  '--oc-viewport-dot-size': '18px 18px',
  '--oc-viewport-dot-position': '9px 9px',
  '--oc-viewport-alignment-snap-distance': '8px',
  '--oc-viewport-alignment-snap-release-distance': '12px',
  '--oc-property-row-height': '28px',
  '--oc-property-row-expanded-height': '112px',
  '--oc-table-row-height': '32px',
  '--oc-data-grid-key-column-width': '232px',
  '--oc-data-grid-column-width': '260px',
  '--oc-data-grid-column-min-width': '180px',
  '--oc-data-grid-column-max-width': '520px',
  '--oc-data-grid-tail-column-width': '40px',
  '--oc-data-grid-column-resize-step': '16px',
  '--oc-data-grid-preload-block-distance': '240px',
  '--oc-data-grid-preload-inline-distance': '520px',
  '--oc-data-grid-z-sticky-column': '3',
  '--oc-data-grid-z-sticky-header': '4',
  '--oc-data-grid-z-corner': '5',
  '--oc-radius-sm': '3px',
  '--oc-radius-md': '6px',
  '--oc-radius-lg': '12px',
  '--oc-radius-full': '999px',
  '--oc-border-width': '1px',
  '--oc-duration-fast': '100ms',
  '--oc-duration-normal': '150ms',
  '--oc-duration-slow': '250ms',
  '--oc-overflow-text-duration': '4s',
  '--oc-ease': 'cubic-bezier(0.2, 0, 0, 1)',
} as const satisfies Partial<OcThemeTokens>

const darkTheme: OcThemeTokens = {
  ...OC_SHARED_THEME_TOKENS,
  '--oc-scrollbar-thumb': 'rgba(156, 156, 156, 0.32)',
  '--oc-scrollbar-thumb-hover': 'rgba(186, 186, 186, 0.48)',

  '--oc-bg-base': '#1e1e1e',
  '--oc-data-grid-bg-inherited': 'var(--oc-bg-base)',
  '--oc-bg-surface': '#252526',
  '--oc-bg-block': '#222223',
  '--oc-bg-raised': '#2d2d2d',

  '--oc-bg-hover': 'rgba(255, 255, 255, 0.04)',
  '--oc-bg-active': 'rgba(162, 96, 255, 0.22)',
  '--oc-bg-selected': 'rgba(162, 96, 255, 0.16)',

  '--oc-bg-input': '#3c3c3c',

  '--oc-bg-accent-hover': 'rgba(162, 96, 255, 0.92)',
  '--oc-bg-accent-subtle': 'rgba(162, 96, 255, 0.12)',

  '--oc-bg-danger-subtle': 'rgba(241, 76, 76, 0.12)',
  '--oc-bg-warning-subtle': 'rgba(210, 153, 34, 0.12)',

  '--oc-bg-glass': 'rgba(28, 28, 28, 0.76)',
  '--oc-bg-modal-backdrop': 'rgba(15, 15, 15, 0.68)',

  '--oc-border-default': '#3a3d41',
  '--oc-border-muted': '#333333',
  '--oc-border-strong': '#51555b',
  '--oc-accent-glow': 'rgba(162, 96, 255, 0.28)',

  '--oc-danger': '#f14c4c',

  '--oc-fg-default': '#cccccc',
  '--oc-fg-muted': '#888888',
  '--oc-fg-subtle': '#666666',
  '--oc-fg-disabled': '#6f6f6f',
  '--oc-fg-accent': '#b8b0ff',
  '--oc-fg-danger': '#f85149',

  '--oc-icon-muted': '#8b949e',
  '--oc-icon-accent': '#9b90ff',
  '--oc-icon-success': '#3fb950',
  '--oc-icon-active': '#58a6ff',
  '--oc-icon-warning': '#d29922',
  '--oc-icon-danger': '#f85149',

  '--oc-icon-file-opencard': 'oklch(77% 0.16 70)',
  '--oc-icon-file-json': 'oklch(80% 0.14 88)',
  '--oc-icon-file-markdown': 'oklch(68% 0.02 255)',
  '--oc-icon-file-typescript': 'oklch(70% 0.15 255)',
  '--oc-icon-file-javascript': 'oklch(84% 0.17 102)',
  '--oc-icon-file-vue': 'oklch(72% 0.14 160)',
  '--oc-icon-file-html': 'oklch(70% 0.18 36)',
  '--oc-icon-file-css': 'oklch(68% 0.14 245)',
  '--oc-icon-file-image': 'oklch(71% 0.18 305)',
  '--oc-icon-file-config': 'oklch(72% 0.14 170)',
  '--oc-icon-folder': 'oklch(66% 0.025 255)',
  '--oc-icon-folder-open': 'oklch(78% 0.14 85)',

  '--oc-icon-block-text': 'oklch(72% 0.14 253)',
  '--oc-icon-block-markdown': 'oklch(71% 0.15 292)',
  '--oc-icon-block-image': 'oklch(71% 0.18 320)',
  '--oc-icon-block-qrcode': 'oklch(76% 0.12 200)',
  '--oc-icon-block-shape': 'oklch(78% 0.14 85)',
  '--oc-icon-block-simple-container': 'oklch(76% 0.17 145)',
  '--oc-icon-block-flow-container': 'oklch(75% 0.15 38)',

  '--oc-shadow-sm': '0 1px 2px rgba(0, 0, 0, 0.18)',
  '--oc-shadow-md': '0 4px 12px rgba(0, 0, 0, 0.28)',
  '--oc-shadow-lg': '0 10px 28px rgba(0, 0, 0, 0.32)',

  '--oc-focus-ring': '0 0 0 2px rgba(162, 96, 255, 0.4)',
}

const lightTheme: OcThemeTokens = {
  ...OC_SHARED_THEME_TOKENS,
  '--oc-scrollbar-thumb': 'rgba(96, 108, 138, 0.3)',
  '--oc-scrollbar-thumb-hover': 'rgba(72, 84, 116, 0.46)',

  '--oc-bg-base': '#f5f6fb',
  '--oc-data-grid-bg-inherited': 'var(--oc-bg-base)',
  '--oc-bg-surface': '#ffffff',
  '--oc-bg-block': '#fbfbfd',
  '--oc-bg-raised': '#f8f9fd',

  '--oc-bg-hover': 'rgba(31, 36, 48, 0.05)',
  '--oc-bg-active': 'rgba(162, 96, 255, 0.18)',
  '--oc-bg-selected': 'rgba(162, 96, 255, 0.12)',

  '--oc-bg-input': '#ffffff',

  '--oc-bg-accent-hover': 'rgba(162, 96, 255, 0.84)',
  '--oc-bg-accent-subtle': 'rgba(162, 96, 255, 0.1)',

  '--oc-bg-danger-subtle': 'rgba(209, 67, 67, 0.1)',
  '--oc-bg-warning-subtle': 'rgba(183, 126, 24, 0.1)',

  '--oc-bg-glass': 'rgba(245, 247, 253, 0.52)',
  '--oc-bg-modal-backdrop': 'rgba(31, 36, 48, 0.38)',

  '--oc-border-default': '#e3e6f2',
  '--oc-border-muted': '#eceef5',
  '--oc-border-strong': '#d0d4e3',
  '--oc-accent-glow': 'rgba(162, 96, 255, 0.35)',

  '--oc-danger': '#d14343',

  '--oc-fg-default': '#1f2430',
  '--oc-fg-muted': '#6d7487',
  '--oc-fg-subtle': '#a0a6b7',
  '--oc-fg-disabled': '#b8bcc9',
  '--oc-fg-accent': '#5a4fd6',
  '--oc-fg-danger': '#cf4444',

  '--oc-icon-muted': '#7f879a',
  '--oc-icon-accent': '#5b6de8',
  '--oc-icon-success': '#1f9d68',
  '--oc-icon-active': '#2563eb',
  '--oc-icon-warning': '#b77e18',
  '--oc-icon-danger': '#cf4444',

  '--oc-icon-file-opencard': 'oklch(62% 0.13 65)',
  '--oc-icon-file-json': 'oklch(64% 0.115 85)',
  '--oc-icon-file-markdown': 'oklch(58% 0.03 265)',
  '--oc-icon-file-typescript': 'oklch(52% 0.18 260)',
  '--oc-icon-file-javascript': 'oklch(64% 0.13 100)',
  '--oc-icon-file-vue': 'oklch(55% 0.12 158)',
  '--oc-icon-file-html': 'oklch(55% 0.17 34)',
  '--oc-icon-file-css': 'oklch(53% 0.14 250)',
  '--oc-icon-file-image': 'oklch(56% 0.2 305)',
  '--oc-icon-file-config': 'oklch(54% 0.1 175)',
  '--oc-icon-folder': 'oklch(56% 0.03 265)',
  '--oc-icon-folder-open': 'oklch(62% 0.11 78)',

  '--oc-icon-block-text': 'oklch(55% 0.2 263)',
  '--oc-icon-block-markdown': 'oklch(54% 0.2 290)',
  '--oc-icon-block-image': 'oklch(57% 0.22 320)',
  '--oc-icon-block-qrcode': 'oklch(56% 0.095 200)',
  '--oc-icon-block-shape': 'oklch(58% 0.11 75)',
  '--oc-icon-block-simple-container': 'oklch(53% 0.15 145)',
  '--oc-icon-block-flow-container': 'oklch(58% 0.17 38)',

  '--oc-shadow-sm': '0 1px 2px rgba(31, 36, 48, 0.1)',
  '--oc-shadow-md': '0 4px 12px rgba(31, 36, 48, 0.14)',
  '--oc-shadow-lg': '0 10px 28px rgba(31, 36, 48, 0.18)',

  '--oc-focus-ring': '0 0 0 2px rgba(162, 96, 255, 0.5)',
}

export const DEFAULT_OC_THEME: OcThemeId = 'dark'

export const OC_THEME_REGISTRY: Record<OcThemeId, OcThemeTokens> = {
  dark: darkTheme,
  light: lightTheme,
}
